(() => {
  'use strict';
  const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
  const number=(v,fallback)=>v===null||v===undefined||v===''?fallback:(Number.isFinite(Number(v))?Number(v):fallback);
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const textOf=r=>norm([r?.n,...(r?.i||[])].join(' '));
  const DIET_BLOCKS={
    vegetariana:['pollo','pavo','ternera','cerdo','jamon','atun','salmon','merluza','gamba','bacalao','sardina'],
    vegana:['pollo','pavo','ternera','cerdo','jamon','atun','salmon','merluza','gamba','bacalao','sardina','huevo','leche','yogur','queso','skyr','whey'],
    pescetariana:['pollo','pavo','ternera','cerdo','jamon'],
    'sin-lactosa':['leche','yogur','queso','skyr','whey','requeson'],
    'sin-gluten':['trigo','pan','pasta','cuscus','tortilla de trigo','avena']
  };
  const slotsFor=count=>({
    3:[['Desayuno',.25],['Comida',.40],['Cena',.35]],
    4:[['Desayuno',.22],['Comida',.34],['Merienda',.14],['Cena',.30]],
    5:[['Desayuno',.20],['Media mañana',.10],['Comida',.32],['Merienda',.12],['Cena',.26]]
  })[count]||slotsFor(4);
  const slotAliases=slot=>slot==='Media mañana'?['Media mañana','Merienda','Desayuno']:[slot];
  function macroTargets(input={},fallback={kcal:2200,protein:160,carbs:250,fat:70}){
    const kcal=number(input?.kcal,number(fallback?.kcal,2200)),protein=number(input?.protein,number(fallback?.protein,160));let carbs=number(input?.carbs,NaN),fat=number(input?.fat,NaN);
    if(!Number.isFinite(carbs)||!Number.isFinite(fat)){fat=number(fallback?.fat,Math.round(kcal*.27/9));carbs=number(fallback?.carbs,Math.max(50,Math.round((kcal-protein*4-fat*9)/4)));}
    return {kcal:clamp(kcal,1200,5000),protein:clamp(protein,40,300),carbs:clamp(carbs,50,800),fat:clamp(fat,30,200)};
  }
  function validatePreferences(input={}){
    const targets=macroTargets(input),meals=Math.trunc(number(input.meals,4)),days=Math.trunc(number(input.days,7));
    if(![3,4,5].includes(meals))throw new Error('Selecciona entre 3 y 5 comidas.');
    if(days<1||days>30)throw new Error('Selecciona entre 1 y 30 días.');
    return {...targets,meals,days,diet:input.diet||'flexible',excluded:Array.isArray(input.excluded)?input.excluded.map(norm).filter(Boolean):String(input.excluded||'').split(',').map(norm).filter(Boolean),pantry:Array.isArray(input.pantry)?input.pantry.map(norm).filter(Boolean):String(input.pantry||'').split(',').map(norm).filter(Boolean),maxTime:clamp(number(input.maxTime,30),10,90),budget:input.budget||'medio',variety:input.variety||'alta'};
  }
  function normalizeRecipeCatalog(catalog){return (Array.isArray(catalog)?catalog:[]).map(recipe=>({id:String(recipe?.id||''),n:String(recipe?.n||recipe?.name||'').trim(),m:(recipe?.m||recipe?.type)==='Snack'?'Merienda':String(recipe?.m||recipe?.type||''),k:number(recipe?.k??recipe?.kcal,0),p:number(recipe?.p,0),c:number(recipe?.c,0),f:number(recipe?.f,0),i:Array.isArray(recipe?.i)?recipe.i:(Array.isArray(recipe?.ingredients)?recipe.ingredients:[]),s:Array.isArray(recipe?.s)?recipe.s:(Array.isArray(recipe?.steps)?recipe.steps:[]),time:number(recipe?.time,0),difficulty:String(recipe?.difficulty||'')})).filter(recipe=>recipe.n&&recipe.m&&recipe.k>0);}
  function allowedRecipes(recipes,prefs){const blocks=[...(DIET_BLOCKS[prefs.diet]||[]),...prefs.excluded].map(norm);return (Array.isArray(recipes)?recipes:[]).filter(r=>{const txt=textOf(r);return !blocks.some(x=>x&&txt.includes(x));});}
  function parseIngredient(raw){const text=String(raw||'').trim(),m=text.match(/^\s*(\d+(?:[.,]\d+)?)\s*(g|kg|ml|l|ud|uds|unidad(?:es)?)\b\s*(?:de\s+)?(.*)$/i);if(!m)return {raw:text,scalable:false};let qty=Number(m[1].replace(',','.')),unit=m[2].toLowerCase(),name=m[3].trim();if(unit==='kg'){qty*=1000;unit='g'}else if(unit==='l'){qty*=1000;unit='ml'}return {raw:text,scalable:true,name,unit,baseQty:qty};}
  function recipeModel(recipe){return {recipe,parsed:(recipe.i||[]).map(parseIngredient)};}
  function baseScore(recipe,slot,share,prefs,usage,seed){const target={k:prefs.kcal*share,p:prefs.protein*share,c:prefs.carbs*share,f:prefs.fat*share},scale=clamp(target.k/Math.max(1,recipe.k),.45,3),txt=textOf(recipe),err=Math.abs(recipe.p*scale-target.p)/Math.max(15,target.p)+Math.abs(recipe.c*scale-target.c)/Math.max(20,target.c)+Math.abs(recipe.f*scale-target.f)/Math.max(8,target.f),used=Math.min(4,usage.get(recipe.n)||0),repeat=used*(prefs.variety==='alta'?.055:prefs.variety==='media'?.03:.012),pantry=prefs.pantry.some(x=>txt.includes(x))?-.12:0,budget=prefs.budget==='bajo'&&/(salmon|gamba|solomillo|atun fresco)/.test(txt)?.2:0,time=prefs.maxTime<=20&&recipe.time>20?.2:0,jitter=((seed*9301+49297)%233280)/233280*.02;return err+repeat+pantry+budget+time+jitter;}
  function pickRecipe(recipes,slot,share,prefs,usage,seed,avoid){let candidates=recipes.filter(r=>slotAliases(slot).includes(r.m)&&r.n!==avoid);if(!candidates.length)candidates=recipes.filter(r=>r.n!==avoid);if(!candidates.length)throw new Error('No quedan recetas compatibles con tus restricciones.');const ranked=candidates.map(r=>({r,score:baseScore(r,slot,share,prefs,usage,seed)})).sort((a,b)=>a.score-b.score||a.r.n.localeCompare(b.r.n,'es'));return ranked[seed%Math.min(4,ranked.length)].r;}
  function solveLinear(matrix,b){const n=b.length,a=matrix.map((row,i)=>[...row,b[i]]);for(let col=0;col<n;col++){let pivot=col;for(let r=col+1;r<n;r++)if(Math.abs(a[r][col])>Math.abs(a[pivot][col]))pivot=r;if(Math.abs(a[pivot][col])<1e-10)return null;[a[col],a[pivot]]=[a[pivot],a[col]];const d=a[col][col];for(let j=col;j<=n;j++)a[col][j]/=d;for(let r=0;r<n;r++)if(r!==col){const f=a[r][col];for(let j=col;j<=n;j++)a[r][j]-=f*a[col][j];}}return a.map(row=>row[n]);}
  function practicalQty(qty,unit='g'){if(/^ud|unidad/.test(unit)){const step=.5;return Math.max(step,Math.round(qty/step)*step)}const step=qty>=50?5:qty>=10?1:.5;return Math.max(step,Math.round(qty/step)*step);}
  function formatIngredient(parsed,scale){if(!parsed.scalable)return parsed.raw;const qty=practicalQty(parsed.baseQty*scale,parsed.unit),shown=Number.isInteger(qty)?qty:qty.toFixed(1),unit=/^ud|unidad/.test(parsed.unit)?'ud':parsed.unit;return `${shown} ${unit}${parsed.name?' de '+parsed.name:''}`;}
  function makeItems(chosen,prefs,slots){return chosen.map((recipe,i)=>({recipe,slot:slots[i][0],model:recipeModel(recipe),scale:clamp((prefs.kcal*slots[i][1])/Math.max(1,recipe.k),.25,4)}));}
  function calcItems(work){return work.map(item=>{const s=item.scale,m={k:item.recipe.k*s,p:item.recipe.p*s,c:item.recipe.c*s,f:item.recipe.f*s},ingredientAmounts=item.model.parsed.map(parsed=>({text:formatIngredient(parsed,s),adjustable:parsed.scalable,qty:parsed.scalable?practicalQty(parsed.baseQty*s,parsed.unit):null,unit:parsed.unit||'',name:parsed.name||''}));return {recipe:item.recipe,slot:item.slot,scale:s,k:Math.round(m.k),p:Math.round(m.p),c:Math.round(m.c),f:Math.round(m.f),ingredientAmounts};});}
  function totals(items){return items.reduce((a,x)=>({k:a.k+x.k,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f}),{k:0,p:0,c:0,f:0});}
  function macroDeviation(t,prefs){return {k:Math.abs(t.k-prefs.kcal)/Math.max(1,prefs.kcal),p:Math.abs(t.p-prefs.protein)/Math.max(1,prefs.protein),c:Math.abs(t.c-prefs.carbs)/Math.max(1,prefs.carbs),f:Math.abs(t.f-prefs.fat)/Math.max(1,prefs.fat)};}
  function macroError(t,prefs){const d=macroDeviation(t,prefs);return d.k+d.p+d.c+d.f;}
  function withinTargets(t,prefs,tolerance={k:.03,p:.04,c:.045,f:.055}){const d=macroDeviation(t,prefs);return d.k<=tolerance.k&&d.p<=tolerance.p&&d.c<=tolerance.c&&d.f<=tolerance.f;}
  function optimizeIngredients(chosen,prefs,slots){const work=makeItems(chosen,prefs,slots),target=[prefs.kcal,prefs.protein,prefs.carbs,prefs.fat],weights=target.map(x=>Math.max(1,x));for(let pass=0;pass<50;pass++){const rendered=calcItems(work),t=totals(rendered),current=[t.k,t.p,t.c,t.f],residual=target.map((x,j)=>(x-current[j])/weights[j]);if(withinTargets(t,prefs,{k:.005,p:.008,c:.01,f:.012}))break;const derivatives=work.map(item=>[item.recipe.k/weights[0],item.recipe.p/weights[1],item.recipe.c/weights[2],item.recipe.f/weights[3]]),gram=Array.from({length:4},(_,r)=>Array.from({length:4},(_,c)=>derivatives.reduce((s,d)=>s+d[r]*d[c],0)+(r===c?2e-4:0))),y=solveLinear(gram,residual);if(!y)break;work.forEach((item,i)=>{let delta=0;for(let j=0;j<4;j++)delta+=derivatives[i][j]*y[j];item.scale=clamp(item.scale+delta,.18,5)});}let best=calcItems(work),bestErr=macroError(totals(best),prefs);for(const step of [.15,.08,.04,.02,.01]){for(let round=0;round<2;round++){work.forEach(item=>{const original=item.scale;let localBest=original,localErr=bestErr;for(const candidate of [original-step,original+step]){item.scale=clamp(candidate,.18,5);const rendered=calcItems(work),err=macroError(totals(rendered),prefs);if(err<localErr){localErr=err;localBest=item.scale;best=rendered;}}item.scale=localBest;bestErr=localErr;});}}return best;}
  function buildDay(pool,prefs,usage,day,forced={}){const slots=slotsFor(prefs.meals);let best=null;const attemptBuild=(activeUsage,attempts,offset=0)=>{for(let attempt=0;attempt<attempts;attempt++){const chosen=slots.map(([slot,share],i)=>forced[i]||pickRecipe(pool,slot,share,prefs,activeUsage,day*137+(attempt+offset)*29+i*13,forced.avoid)),items=optimizeIngredients(chosen,prefs,slots),t=totals(items),err=macroError(t,prefs);if(!best||err<best.err)best={items,t,err};if(withinTargets(t,prefs))break;}};attemptBuild(usage,160);if(!best||!withinTargets(best.t,prefs))attemptBuild(new Map(),280,160);best.items.forEach(x=>usage.set(x.recipe.n,(usage.get(x.recipe.n)||0)+1));return {day:day+1,items:best.items,totals:best.t,error:best.err,withinTarget:withinTargets(best.t,prefs)};}
  function sameMacroBand(t,reference){const limits={k:.015,p:.02,c:.025,f:.03};return ['k','p','c','f'].every(key=>Math.abs(t[key]-reference[key])/Math.max(1,reference[key])<=limits[key]);}
  function generateDays(recipes,input){const prefs=validatePreferences(input),pool=allowedRecipes(recipes,prefs);if(pool.length<4)throw new Error('Las restricciones dejan muy pocas recetas. Revisa las exclusiones.');const usage=new Map(),reference=buildDay(pool,prefs,new Map(),0),days=[reference],slots=slotsFor(prefs.meals);for(let day=1;day<prefs.days;day++){let built=buildDay(pool,prefs,usage,day);if(!withinTargets(built.totals,prefs)||!sameMacroBand(built.totals,reference.totals)){const items=optimizeIngredients(reference.items.map(x=>x.recipe),prefs,slots),t=totals(items);built={day:day+1,items,totals:t,error:macroError(t,prefs),withinTarget:withinTargets(t,prefs),fallback:true};}days.push(built);}return {createdAt:new Date().toISOString(),preferences:prefs,days};}
  const generate30Days=(recipes,input)=>generateDays(recipes,{...input,days:30});
  function swapMeal(plan,recipes,dayIndex,itemIndex){if(!plan?.days?.[dayIndex])throw new Error('Día no válido.');const prefs=validatePreferences({...plan.preferences,days:plan.days.length}),pool=allowedRecipes(recipes,prefs),day=plan.days[dayIndex],old=day.items[itemIndex],slots=slotsFor(prefs.meals);let candidates=pool.filter(r=>slotAliases(old.slot).includes(r.m)&&r.n!==old.recipe.n);if(!candidates.length)candidates=pool.filter(r=>r.n!==old.recipe.n);if(!candidates.length)throw new Error('No hay una alternativa equivalente disponible.');let best=null;candidates.slice(0,60).forEach(r=>{const chosen=day.items.map((x,i)=>i===itemIndex?r:x.recipe),items=optimizeIngredients(chosen,prefs,slots),t=totals(items),err=macroError(t,prefs);if(!best||err<best.err)best={items,t,err};});if(!best)throw new Error('No se pudo calcular una alternativa equivalente.');plan.days[dayIndex]={day:day.day,items:best.items,totals:best.t,error:best.err,withinTarget:withinTargets(best.t,prefs)};return plan;}
  function legacyScaleIngredient(raw,scale){const parsed=parseIngredient(raw);return parsed.scalable?formatIngredient(parsed,scale):parsed.raw;}
  function ingredientsFor(item){if(Array.isArray(item?.ingredientAmounts)&&item.ingredientAmounts.length)return item.ingredientAmounts.map(x=>x.text);return (item?.recipe?.i||[]).map(raw=>legacyScaleIngredient(raw,item?.scale||1));}
  function shoppingByWeek(plan,week=0){const start=week*7,end=Math.min(start+7,plan?.days?.length||0),map=new Map();(plan?.days||[]).slice(start,end).flatMap(d=>d.items).forEach(item=>ingredientsFor(item).forEach(raw=>{const key=norm(raw).replace(/^\d+[\d.,/]*\s*(g|kg|ml|l|ud|uds|unidad(?:es)?)?\s*(de\s*)?/,'').trim()||norm(raw);if(!map.has(key))map.set(key,{name:raw,count:0});map.get(key).count+=1;}));return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'));}
  globalThis.RecompMealPlanner={macroTargets,validatePreferences,normalizeRecipeCatalog,allowedRecipes,generateDays,generate30Days,swapMeal,ingredientsFor,shoppingByWeek,totals,recipeModel,practicalQty,macroDeviation,withinTargets};
})();