(() => {
  'use strict';
  const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
  const number=(v,fallback)=>Number.isFinite(Number(v))?Number(v):fallback;
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const textOf=r=>norm([r?.n,...(r?.i||[])].join(' '));
  const DIET_BLOCKS={
    vegetariana:['pollo','pavo','ternera','cerdo','jamon','atun','salmon','merluza','gamba','bacalao','sardina'],
    vegana:['pollo','pavo','ternera','cerdo','jamon','atun','salmon','merluza','gamba','bacalao','sardina','huevo','leche','yogur','queso','skyr','whey'],
    pescetariana:['pollo','pavo','ternera','cerdo','jamon'],
    'sin-lactosa':['leche','yogur','queso','skyr','whey','requeson'],
    'sin-gluten':['trigo','pan','pasta','cuscus','tortilla de trigo','avena']
  };
  const slotsFor=count=>({
    3:[['Desayuno',.25],['Comida',.40],['Cena',.35]],
    4:[['Desayuno',.22],['Comida',.34],['Merienda',.14],['Cena',.30]],
    5:[['Desayuno',.20],['Media mañana',.10],['Comida',.32],['Merienda',.12],['Cena',.26]]
  })[count]||slotsFor(4);
  const slotAliases=slot=>slot==='Media mañana'?['Media mañana','Merienda','Desayuno']:[slot];
  const FOODS=[
    ['aceite de oliva',884,0,0,100],['aceite',884,0,0,100],['pechuga de pollo',165,31,0,3.6],['pollo',165,31,0,3.6],['pavo',135,29,0,1.6],
    ['ternera',200,26,0,10],['carne picada',215,26,0,12],['cerdo',195,27,0,9],['salmon',208,20,0,13],['atun',132,29,0,1],['merluza',90,18,0,2],['bacalao',82,18,0,0.7],['gamba',99,24,0.2,0.3],
    ['arroz',130,2.7,28,0.3],['pasta integral',149,5.5,30,1.4],['pasta',157,5.8,31,0.9],['patata',87,1.9,20,0.1],['boniato',90,2,21,0.2],['quinoa',120,4.4,21.3,1.9],['cuscus',112,3.8,23.2,0.2],['pan integral',247,13,41,4.2],['pan',265,9,49,3.2],['tortilla integral',290,8,49,7],
    ['avena',379,13.2,67.7,6.5],['cereales',370,8,78,3],['muesli',370,10,65,8],['lentejas',116,9,20,0.4],['garbanzos',164,8.9,27.4,2.6],['alubias',127,8.7,22.8,0.5],['judias',127,8.7,22.8,0.5],
    ['huevo',143,12.6,0.7,9.5],['claras',52,10.9,0.7,0.2],['skyr',63,11,4,0.2],['yogur griego',97,9,3.9,5],['yogur',63,5.3,7,1.6],['leche',47,3.3,4.8,1.6],['queso fresco',98,12,3,4],['queso',280,25,2,20],
    ['whey',390,78,8,6],['proteina en polvo',390,78,8,6],['tofu',144,17,2.8,8.7],['tempeh',193,20.3,7.6,10.8],['aguacate',160,2,8.5,14.7],['almendras',579,21.2,21.6,49.9],['nueces',654,15.2,13.7,65.2],['cacahuete',567,25.8,16.1,49.2],['crema de cacahuete',588,25,20,50],
    ['platano',89,1.1,22.8,0.3],['manzana',52,0.3,13.8,0.2],['frutos rojos',50,1,12,0.4],['fresas',32,0.7,7.7,0.3]
  ].map(([name,k,p,c,f])=>({name:norm(name),k,p,c,f}));
  function macroTargets(input={},fallback={kcal:2200,protein:160,carbs:250,fat:70}){
    const kcal=number(input?.kcal,number(fallback?.kcal,2200)),protein=number(input?.protein,number(fallback?.protein,160));let carbs=number(input?.carbs,NaN),fat=number(input?.fat,NaN);
    if(!Number.isFinite(carbs)||!Number.isFinite(fat)){fat=number(fallback?.fat,Math.round(kcal*.27/9));carbs=number(fallback?.carbs,Math.max(50,Math.round((kcal-protein*4-fat*9)/4)));}
    return {kcal:clamp(kcal,1200,5000),protein:clamp(protein,40,300),carbs:clamp(carbs,50,800),fat:clamp(fat,30,200)};
  }
  function validatePreferences(input={}){
    const targets=macroTargets(input),meals=Math.trunc(number(input.meals,4)),days=Math.trunc(number(input.days,7));if(![3,4,5].includes(meals))throw new Error('Selecciona entre 3 y 5 comidas.');if(days<1||days>30)throw new Error('Selecciona entre 1 y 30 días.');
    return {...targets,meals,days,diet:input.diet||'flexible',excluded:Array.isArray(input.excluded)?input.excluded.map(norm).filter(Boolean):String(input.excluded||'').split(',').map(norm).filter(Boolean),pantry:Array.isArray(input.pantry)?input.pantry.map(norm).filter(Boolean):String(input.pantry||'').split(',').map(norm).filter(Boolean),maxTime:clamp(number(input.maxTime,30),10,90),budget:input.budget||'medio',variety:input.variety||'alta'};
  }
  function normalizeRecipeCatalog(catalog){return (Array.isArray(catalog)?catalog:[]).map(recipe=>({id:String(recipe?.id||''),n:String(recipe?.n||recipe?.name||'').trim(),m:(recipe?.m||recipe?.type)==='Snack'?'Merienda':String(recipe?.m||recipe?.type||''),k:number(recipe?.k??recipe?.kcal,0),p:number(recipe?.p,0),c:number(recipe?.c,0),f:number(recipe?.f,0),i:Array.isArray(recipe?.i)?recipe.i:(Array.isArray(recipe?.ingredients)?recipe.ingredients:[]),s:Array.isArray(recipe?.s)?recipe.s:(Array.isArray(recipe?.steps)?recipe.steps:[]),time:number(recipe?.time,0),difficulty:String(recipe?.difficulty||'')})).filter(recipe=>recipe.n&&recipe.m&&recipe.k>0);}
  function allowedRecipes(recipes,prefs){const blocks=[...(DIET_BLOCKS[prefs.diet]||[]),...prefs.excluded].map(norm);return (Array.isArray(recipes)?recipes:[]).filter(r=>{const txt=textOf(r);return !blocks.some(x=>x&&txt.includes(x));});}
  function foodFor(name){const n=norm(name);return FOODS.find(food=>n.includes(food.name))||null;}
  function parseIngredient(raw){const text=String(raw||'').trim(),m=text.match(/^\s*(\d+(?:[.,]\d+)?)\s*(g|kg|ml|l|ud|uds|unidad(?:es)?)\b\s*(?:de\s+)?(.*)$/i);if(!m)return {raw:text,adjustable:false};let qty=Number(m[1].replace(',','.')),unit=m[2].toLowerCase(),name=m[3].trim();if(unit==='kg'){qty*=1000;unit='g'}else if(unit==='l'){qty*=1000;unit='ml'};const food=foodFor(name);if(!food)return {raw:text,adjustable:false};if(/^ud|unidad/.test(unit)){if(food.name.includes('huevo')){qty*=50;unit='g'}else return {raw:text,adjustable:false};}return {raw:text,adjustable:true,name,unit,baseQty:qty,food};}
  const nutrient=(food,qty)=>({k:food.k*qty/100,p:food.p*qty/100,c:food.c*qty/100,f:food.f*qty/100}),add=(a,b)=>({k:a.k+b.k,p:a.p+b.p,c:a.c+b.c,f:a.f+b.f}),sub=(a,b)=>({k:a.k-b.k,p:a.p-b.p,c:a.c-b.c,f:a.f-b.f}),mul=(a,s)=>({k:a.k*s,p:a.p*s,c:a.c*s,f:a.f*s});
  function recipeModel(recipe){const parsed=(recipe.i||[]).map(parseIngredient),adjustable=parsed.filter(x=>x.adjustable),known=adjustable.reduce((t,x)=>add(t,nutrient(x.food,x.baseQty)),{k:0,p:0,c:0,f:0}),residual=sub({k:recipe.k,p:recipe.p,c:recipe.c,f:recipe.f},known);return {recipe,parsed,adjustable,residual};}
  function baseScore(recipe,slot,share,prefs,usage,seed){const target={k:prefs.kcal*share,p:prefs.protein*share,c:prefs.carbs*share,f:prefs.fat*share},scale=clamp(target.k/Math.max(1,recipe.k),.55,2.2),txt=textOf(recipe),err=Math.abs(recipe.p*scale-target.p)/Math.max(15,target.p)+Math.abs(recipe.c*scale-target.c)/Math.max(20,target.c)+Math.abs(recipe.f*scale-target.f)/Math.max(8,target.f),repeat=(usage.get(recipe.n)||0)*(prefs.variety==='alta'?.42:prefs.variety==='media'?.24:.10),pantry=prefs.pantry.some(x=>txt.includes(x))?-.16:0,budget=prefs.budget==='bajo'&&/(salmon|gamba|solomillo|atun fresco)/.test(txt)?.3:0,time=prefs.maxTime<=20&&recipe.time>20?.3:0,jitter=((seed*9301+49297)%233280)/233280*.06;return err+repeat+pantry+budget+time+jitter;}
  function pickRecipe(recipes,slot,share,prefs,usage,seed,avoid){let candidates=recipes.filter(r=>slotAliases(slot).includes(r.m)&&r.n!==avoid);if(!candidates.length)candidates=recipes.filter(r=>r.n!==avoid);if(!candidates.length)throw new Error('No quedan recetas compatibles con tus restricciones.');const ranked=candidates.map(r=>({r,score:baseScore(r,slot,share,prefs,usage,seed)})).sort((a,b)=>a.score-b.score||a.r.n.localeCompare(b.r.n,'es'));return ranked[seed%Math.min(5,ranked.length)].r;}
  function solveLinear(matrix,b){const n=b.length,a=matrix.map((row,i)=>[...row,b[i]]);for(let col=0;col<n;col++){let pivot=col;for(let r=col+1;r<n;r++)if(Math.abs(a[r][col])>Math.abs(a[pivot][col]))pivot=r;if(Math.abs(a[pivot][col])<1e-10)return null;[a[col],a[pivot]]=[a[pivot],a[col]];const d=a[col][col];for(let j=col;j<=n;j++)a[col][j]/=d;for(let r=0;r<n;r++)if(r!==col){const f=a[r][col];for(let j=col;j<=n;j++)a[r][j]-=f*a[col][j];}}return a.map(row=>row[n]);}
  function makeVariables(chosen,prefs,slots){return chosen.map((recipe,i)=>{const model=recipeModel(recipe),baseScale=clamp((prefs.kcal*slots[i][1])/Math.max(1,recipe.k),.45,2.6);return {recipe,slot:slots[i][0],model,baseScale,vars:model.adjustable.map(ing=>({ing,factor:baseScale,min:.3,max:3.6}))};});}
  function formatIngredient(parsed,qty){const unit=parsed.unit==='ml'?'ml':'g',step=qty>=50?5:qty>=10?1:.5,shown=Math.max(step,Math.round(qty/step)*step);return `${Number.isInteger(shown)?shown:shown.toFixed(1)} ${unit} de ${parsed.name}`;}
  function calcItems(items){return items.map(item=>{let m=mul(item.model.residual,item.baseScale);const ingredientAmounts=item.model.parsed.map(parsed=>{if(!parsed.adjustable)return {text:parsed.raw,adjustable:false};const variable=item.vars.find(v=>v.ing===parsed),qty=parsed.baseQty*variable.factor;m=add(m,nutrient(parsed.food,qty));return {text:formatIngredient(parsed,qty),adjustable:true,qty,unit:parsed.unit,name:parsed.name};});return {recipe:item.recipe,slot:item.slot,scale:item.baseScale,k:Math.round(m.k),p:Math.round(m.p),c:Math.round(m.c),f:Math.round(m.f),ingredientAmounts};});}
  function optimizeIngredients(chosen,prefs,slots){const work=makeVariables(chosen,prefs,slots),vars=work.flatMap(item=>item.vars.map(v=>({item,v}))),target=[prefs.kcal,prefs.protein,prefs.carbs,prefs.fat],weights=target.map(x=>Math.max(1,x));for(let pass=0;pass<14;pass++){const rendered=calcItems(work),t=totals(rendered),current=[t.k,t.p,t.c,t.f],residual=target.map((x,j)=>(x-current[j])/weights[j]);if(residual.every(x=>Math.abs(x)<.0025)||!vars.length)break;const derivatives=vars.map(({v})=>{const n=nutrient(v.ing.food,v.ing.baseQty);return [n.k/weights[0],n.p/weights[1],n.c/weights[2],n.f/weights[3]]}),gram=Array.from({length:4},(_,r)=>Array.from({length:4},(_,c)=>derivatives.reduce((s,d)=>s+d[r]*d[c],0)+(r===c?1e-5:0))),y=solveLinear(gram,residual);if(!y)break;vars.forEach(({v},i)=>{let delta=0;for(let j=0;j<4;j++)delta+=derivatives[i][j]*y[j];v.factor=clamp(v.factor+delta,v.min,v.max)});}return calcItems(work);}
  function totals(items){return items.reduce((a,x)=>({k:a.k+x.k,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f}),{k:0,p:0,c:0,f:0});}
  function macroError(t,prefs){return Math.abs(t.k-prefs.kcal)/prefs.kcal+Math.abs(t.p-prefs.protein)/prefs.protein+Math.abs(t.c-prefs.carbs)/prefs.carbs+Math.abs(t.f-prefs.fat)/prefs.fat;}
  function buildDay(pool,prefs,usage,day,forced={}){const slots=slotsFor(prefs.meals);let best=null;for(let attempt=0;attempt<72;attempt++){const chosen=slots.map(([slot,share],i)=>forced[i]||pickRecipe(pool,slot,share,prefs,usage,day*97+attempt*19+i*7,forced.avoid)),items=optimizeIngredients(chosen,prefs,slots),t=totals(items),err=macroError(t,prefs);if(!best||err<best.err)best={items,t,err};if(err<.018)break;}best.items.forEach(x=>usage.set(x.recipe.n,(usage.get(x.recipe.n)||0)+1));return {day:day+1,items:best.items,totals:best.t,error:best.err};}
  function generateDays(recipes,input){const prefs=validatePreferences(input),pool=allowedRecipes(recipes,prefs);if(pool.length<4)throw new Error('Las restricciones dejan muy pocas recetas. Revisa las exclusiones.');const usage=new Map(),days=Array.from({length:prefs.days},(_,day)=>buildDay(pool,prefs,usage,day));return {createdAt:new Date().toISOString(),preferences:prefs,days};}
  const generate30Days=(recipes,input)=>generateDays(recipes,{...input,days:30});
  function swapMeal(plan,recipes,dayIndex,itemIndex){if(!plan?.days?.[dayIndex])throw new Error('Día no válido.');const prefs=validatePreferences({...plan.preferences,days:plan.days.length}),pool=allowedRecipes(recipes,prefs),day=plan.days[dayIndex],old=day.items[itemIndex],slots=slotsFor(prefs.meals);let candidates=pool.filter(r=>slotAliases(old.slot).includes(r.m)&&r.n!==old.recipe.n);if(!candidates.length)candidates=pool.filter(r=>r.n!==old.recipe.n);if(!candidates.length)throw new Error('No hay una alternativa equivalente disponible.');const ranked=candidates.map(r=>{const scale=clamp(old.k/Math.max(1,r.k),.4,3),e=Math.abs(r.p*scale-old.p)/Math.max(10,old.p)+Math.abs(r.c*scale-old.c)/Math.max(15,old.c)+Math.abs(r.f*scale-old.f)/Math.max(6,old.f);return {r,e};}).sort((a,b)=>a.e-b.e).slice(0,30);let best=null;ranked.forEach(({r,e})=>{const chosen=day.items.map((x,i)=>i===itemIndex?r:x.recipe),items=optimizeIngredients(chosen,prefs,slots),t=totals(items),err=macroError(t,prefs)+e*.04;if(!best||err<best.err)best={items,t,err};});if(!best)throw new Error('No se pudo calcular una alternativa equivalente.');plan.days[dayIndex]={day:day.day,items:best.items,totals:best.t,error:best.err};return plan;}
  function legacyScaleIngredient(raw,scale){const text=String(raw||'').trim(),m=text.match(/^\s*(\d+(?:[.,]\d+)?)\s*(g|kg|ml|l)\b\s*(.*)$/i);if(!m)return text;let value=Number(m[1].replace(',','.'))*scale,unit=m[2],rest=m[3];if(/^kg$/i.test(unit)){value*=1000;unit='g'}if(/^l$/i.test(unit)){value*=1000;unit='ml'}return `${Math.max(1,Math.round(value))} ${unit}${rest?' '+rest:''}`;}
  function ingredientsFor(item){if(Array.isArray(item?.ingredientAmounts)&&item.ingredientAmounts.length)return item.ingredientAmounts.map(x=>x.text);return (item?.recipe?.i||[]).map(raw=>legacyScaleIngredient(raw,item?.scale||1));}
  function shoppingByWeek(plan,week=0){const start=week*7,end=Math.min(start+7,plan?.days?.length||0),map=new Map();(plan?.days||[]).slice(start,end).flatMap(d=>d.items).forEach(item=>ingredientsFor(item).forEach(raw=>{const key=norm(raw).replace(/^\d+[\d.,/]*\s*(g|kg|ml|l|ud|uds|unidad(?:es)?)?\s*(de\s*)?/,'').trim()||norm(raw);if(!map.has(key))map.set(key,{name:raw,count:0});map.get(key).count+=1;}));return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'));}
  globalThis.RecompMealPlanner={macroTargets,validatePreferences,normalizeRecipeCatalog,allowedRecipes,generateDays,generate30Days,swapMeal,ingredientsFor,shoppingByWeek,totals,recipeModel};
})();
