(function(root,factory){'use strict';const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.RecompQualityV54=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){'use strict';
const finite=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
function expectedMeals(input={},plan={}){const raw=input.meals??plan.preferences?.meals;if(raw==null||raw==='')return null;return Math.min(6,Math.max(3,Math.round(finite(raw,4))));}
function validatePlan(plan,input={}){if(!plan||!Array.isArray(plan.days))throw new Error('El plan nutricional no contiene días válidos.');const expected=expectedMeals(input,plan),requestedDays=input.days==null?null:Math.min(30,Math.max(1,Math.round(finite(input.days,30))));if(requestedDays!==null&&plan.days.length!==requestedDays)throw new Error(`El plan nutricional está incompleto: se solicitaron ${requestedDays} días y se generaron ${plan.days.length}.`);for(const [index,day] of plan.days.entries()){const count=Array.isArray(day?.items)?day.items.length:0;if(count<3||count>6)throw new Error(`El día ${index+1} contiene ${count} comidas; Recomp requiere entre 3 y 6 para mantener un reparto energético seguro.`);if(expected!==null&&count!==expected)throw new Error(`El día ${index+1} está incompleto: esperabas ${expected} comidas y se generaron ${count}.`);const shares=day.energyDistribution?.shares;if(Array.isArray(shares)&&shares.length!==count)throw new Error(`El día ${index+1} tiene un reparto energético inconsistente con sus comidas.`);}return plan;}
function install(){const planner=root?.RecompMealPlanner;if(!planner||planner.__qualityV54)return false;const generate=planner.generateDays?.bind(planner),swap=planner.swapMeal?.bind(planner);if(typeof generate==='function')planner.generateDays=(recipes,input={})=>validatePlan(generate(recipes,input),input);if(typeof swap==='function')planner.swapMeal=(plan,recipes,dayIndex,itemIndex)=>validatePlan(swap(plan,recipes,dayIndex,itemIndex),plan?.preferences||{});if(typeof planner.generate30Days==='function')planner.generate30Days=(recipes,input={})=>planner.generateDays(recipes,{...input,days:30});planner.validatePlanV54=validatePlan;planner.__qualityV54=true;return true;}
function boot(){install();}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}else install();
return{install,validatePlan,expectedMeals};
});
