const { test, expect } = require('@playwright/test');
async function noOverflow(page,label=''){const d=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(d.scroll,`${label} ${JSON.stringify(d)}`).toBeLessThanOrEqual(d.client+2)}
async function completeIntake(page){for(let i=0;i<3;i++){await noOverflow(page,`intake-${i}`);await page.locator('#rNext').click()}await noOverflow(page,'intake-generate');await page.locator('#rGenerate').click();await page.waitForFunction(()=>localStorage.getItem('recomp_unified_profile_v2')!==null)}
for(const width of [320,375,390,430]) test(`Recomp 10 fits ${width}px without horizontal overflow`,async({browser})=>{const context=await browser.newContext({viewport:{width,height:820},isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await noOverflow(page,'launch');await completeIntake(page);await page.waitForFunction(()=>Boolean(window.RecompQualityV53));await noOverflow(page,'home');const buttons=page.locator('nav button');const count=await buttons.count();for(let i=0;i<count;i++){const b=buttons.nth(i);if(await b.isVisible()){await b.click();await page.waitForTimeout(40);await noOverflow(page,`nav-${i}`)}}expect(await page.locator('nav .navicon svg').count()).toBeGreaterThanOrEqual(6);await context.close()});

test('Recomp nutrition dashboard stays entirely inside a 390px iPhone viewport',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await completeIntake(page);await page.locator('nav button').filter({hasText:'Nutrición'}).click();await expect(page.locator('#rnNutritionHeader')).toBeVisible();await noOverflow(page,'nutrition-dashboard');const boxes=await page.locator('#rnNutritionHeader .rn-hero,#rnNutritionHeader .rn-actions button,#rnNutritionHeader .rn-macro,nav,.r10Fab').evaluateAll(nodes=>nodes.filter(el=>getComputedStyle(el).display!=='none').map(el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width,text:(el.textContent||'').trim().slice(0,32)}}));for(const b of boxes){expect(b.left,`${b.text} left clipped`).toBeGreaterThanOrEqual(-1);expect(b.right,`${b.text} right clipped`).toBeLessThanOrEqual(391);expect(b.width,`${b.text} collapsed`).toBeGreaterThan(40)}const macroCols=await page.locator('.rn-macros').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length);expect(macroCols).toBe(2);await context.close()});

test('Recomp menu cards keep readable meal column on iPhone width',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await completeIntake(page);await page.locator('nav button').filter({hasText:'Menús'}).click();await expect(page.locator('#mpGenerate')).toBeVisible();await page.locator('#mpDays').fill('1');await page.locator('#mpGenerate').click();await page.waitForSelector('.mp-meal');await noOverflow(page,'menu-generated');const meal=page.locator('.mp-meal').first();const recipe=meal.locator('.mp-recipe-link');const box=await recipe.boundingBox();expect(box?.width||0,'recipe text column collapsed').toBeGreaterThan(190);const metrics=await recipe.evaluate(el=>({wordBreak:getComputedStyle(el).wordBreak,whiteSpace:getComputedStyle(el).whiteSpace,scroll:el.scrollWidth,client:el.clientWidth}));expect(metrics.wordBreak).not.toBe('break-all');expect(metrics.whiteSpace).toBe('normal');expect(metrics.scroll).toBeLessThanOrEqual(metrics.client+2);await context.close()});

test('Recomp 10 v53 rejects pathological calorie concentration',async({page})=>{await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.RecompQualityV53));const result=await page.evaluate(()=>{const d={items:[{k:200,p:15,c:20,f:6,scale:1},{k:1776,p:100,c:220,f:55,scale:3},{k:160,p:10,c:20,f:4,scale:1},{k:264,p:20,c:25,f:8,scale:1}],totals:{k:2400,p:145,c:285,f:73}};const x=RecompQualityV53.rebalanceDay(d,{kcal:2400,protein:170,carbs:285,fat:75});return{x:x.items.map(i=>i.k),max:Math.max(...x.items.map(i=>i.k/x.totals.k)),total:x.totals.k}});expect(result.x).toEqual([528,816,336,720]);expect(result.max).toBeLessThanOrEqual(.34);expect(result.total).toBe(2400)});
